package com.example.myapplication.constantes;

public interface Mandelin {

    int MANDELIN_RED_MDMA = 55;
    int MANDELIN_GREEN_MDMA = 54;
    int MANDELIN_BLUE_MDMA = 54;
    String MANDELIN_SMDMA = "MDMA";

    int MANDELIN_RED_MDE = 56;
    int MANDELIN_GREEN_MDE = 54;
    int MANDELIN_BLUE_MDE = 54;
    String MANDELIN_SMDE = "MDE";

    int MANDELIN_RED_SASS = 56;
    int MANDELIN_GREEN_SASS = 54;
    int MANDELIN_BLUE_SASS = 54;
    String MANDELIN_SSASS = "MDA (Sass)";

    int MANDELIN_RED_5APB = 55;
    int MANDELIN_GREEN_5APB = 54;
    int MANDELIN_BLUE_5APB = 54;
    String MANDELIN_S5APB = "5-APB";

    int MANDELIN_RED_6APB = 55;
    int MANDELIN_GREEN_6APB = 54;
    int MANDELIN_BLUE_6APB = 54;
    String MANDELIN_S6APB = "6-APB";

    int MANDELIN_RED_DXM = 256;
    int MANDELIN_GREEN_DXM = 256;
    int MANDELIN_BLUE_DXM = 256;
    String MANDELIN_SDXM = "DXM";

    int MANDELIN_RED_ETHYLONE = 171;
    int MANDELIN_GREEN_ETHYLONE = 170;
    int MANDELIN_BLUE_ETHYLONE = 170;
    String MANDELIN_SETHYLONE = "Ethylone";

    int MANDELIN_RED_SUGAR = 179;
    int MANDELIN_GREEN_SUGAR = 161;
    int MANDELIN_BLUE_SUGAR = 161;
    String MANDELIN_SSUGAR = "Sugar";

    int MANDELIN_RED_METHYLONE = 207;
    int MANDELIN_GREEN_METHYLONE = 131;
    int MANDELIN_BLUE_METHYLONE = 131;
    String MANDELIN_SMETHYLONE = "Methylone";

    int MANDELIN_RED_BUTYLONE = 112;
    int MANDELIN_GREEN_BUTYLONE = 98;
    int MANDELIN_BLUE_BUTYLONE = 98;
    String MANDELIN_SBUTYLONE = "Butylone";

    int MANDELIN_RED_MDPV = 62;
    int MANDELIN_GREEN_MDPV = 70;
    int MANDELIN_BLUE_MDPVE = 70;
    String MANDELIN_SMDPV = "MDPV";

    int MANDELIN_RED_METANPHETAMINE= 47;
    int  MANDELIN_GREEN_METANPHETAMINE = 95;
    int MANDELIN_BLUE_METANPHETAMINE = 95;
    String MANDELIN_SMETAMPHETAMINE = "Metamphetamine";

    int MANDELIN_RED_AMPHETAMINE= 47;
    int  MANDELIN_GREEN_AMPHETAMINE = 95;
    int MANDELIN_BLUE_AMPHETAMINE = 95;
    String MANDELIN_SAMPHETAMINE = "Amphetamin";

    int MANDELIN_RED_MESCALINE= 149;
    int  MANDELIN_GREEN_MESCALINE = 128;
    int MANDELIN_BLUE_MESCALINE = 128;
    String MANDELIN_S3 = " Mescaline";

    int MANDELIN_RED_CODEYNE = 228;
    int MANDELIN_GREEN_CODEYNE = 153;
    int MANDELIN_BLUE_CODEYNE = 153;
    String MANDELIN_SCODEYNE = "Codeyne";

    int MANDELIN_RED_MORPHINE = 256;
    int MANDELIN_GREEN_MORPHINE = 256;
    int MANDELIN_BLUE_MORPHINE = 256;
    String MANDELIN_SMORPHINE = "Morphine";

    int MANDELIN_RED_OXYCODONE = 75;
    int MANDELIN_GREEN_OXYCODONE = 90;
    int MANDELIN_BLUE_OXYCODONE = 90;
    String MANDELIN_SOXYCODONE = "Oxycodone";

    int MANDELIN_RED_ACB = 216;
    int MANDELIN_GREEN_ACB = 225;
    int MANDELIN_BLUE_ACB = 225;
    String MANDELIN_S5 = "aC-B";

    int MANDELIN_RED_AC1 = 67;
    int MANDELIN_GREEN_AC1 = 52;
    int MANDELIN_BLUE_AC1 = 52;
    String MANDELIN_SAC1 = "aC-I";

    int MANDELIN_RED_HEROIN = 179;
    int MANDELIN_GREEN_HEROIN = 90;
    int MANDELIN_BLUE_HEROIN = 90;
    String MANDELIN_SHEROIN = "Heroin";

    int MANDELIN_RED_ASPIRIN = 98;
    int MANDELIN_GREEN_ASPIRIN = 95;
    int MANDELIN_BLUE_ASPIRIN = 95;
    String MANDELIN_SASPIRIN = "Aspirin";

    int MANDELIN_REDNR = 256;
    int MANDELIN_GREENNR = 256;
    int MANDELIN_BLUENR = 256;
    String MANDELIN_NR = "SIN REACCIÓN";

}
